"""Real editor/document pipeline evidence: Draw.io, XeLaTeX compile, DOCX export."""
from __future__ import annotations

import asyncio
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))


DRAWIO_SOURCE = """<mxfile host="app.diagrams.net"><diagram name="Page-1"><mxGraphModel dx="800" dy="600" grid="1" page="1" pageWidth="827" pageHeight="1169"><root><mxCell id="0"/><mxCell id="1" parent="0"/><mxCell id="2" value="Input" style="rounded=1;whiteSpace=wrap;html=1;" vertex="1" parent="1"><mxGeometry x="80" y="100" width="120" height="60" as="geometry"/></mxCell><mxCell id="3" value="Output" style="rounded=1;whiteSpace=wrap;html=1;" vertex="1" parent="1"><mxGeometry x="300" y="100" width="120" height="60" as="geometry"/></mxCell></root></mxGraphModel></diagram></mxfile>"""


def test_editor_drawio_compile_and_docx_export_persist_artifacts(tmp_path, monkeypatch):
    import services.editor_ai as editor_ai
    import services.state_store as store
    from routers.docx_export import export_docx, DocxExportRequest
    from services.docx_tool_loader import get_markdown_to_docx

    workspace_root = tmp_path / "workspaces"
    workspace_root.mkdir()
    drawio_runtime = ROOT / "runtime" / "draw.io"
    pandoc_bin = ROOT / "runtime" / "pandoc" / "pandoc.exe"
    monkeypatch.setattr(editor_ai, "WORKSPACES_DIR", workspace_root)
    monkeypatch.setattr(editor_ai, "RUNTIME_DRAWIO", drawio_runtime)
    if pandoc_bin.is_file():
        monkeypatch.setattr(editor_ai, "PANDOC_BIN", str(pandoc_bin))
    monkeypatch.setattr("config.WORKSPACES_DIR", workspace_root)
    monkeypatch.setattr("routers.docx_export.WORKSPACES_DIR", workspace_root)

    wf_id = "docpipe01"
    workspace = workspace_root / wf_id
    paper = workspace / "paper"
    paper.mkdir(parents=True)

    async def go():
        # Draw.io → real PNG/PDF artifacts with provenance manifest.
        drawio = await editor_ai.drawio_export(wf_id, DRAWIO_SOURCE, "png")
        assert drawio["status"] == "completed"
        assert drawio["outputs"]
        output0 = drawio["outputs"][0]
        png_rel = output0.get("path") or output0.get("source", {}).get("path")
        assert png_rel
        png_path = workspace / png_rel
        assert png_path.is_file() and png_path.stat().st_size > 1000
        assert png_path.read_bytes()[:8] == b"\x89PNG\r\n\x1a\n"
        assert (workspace / drawio["manifest"]["path"]).is_file()

        # Markdown source for compile + DOCX.
        md = (
            "# Document Pipeline Gate\n\n"
            "This paragraph validates local compilation and export.\n\n"
            "## Results\n\n"
            "The diagram below is generated by Draw.io.\n\n"
            f"![pipeline]({png_path.relative_to(workspace).as_posix()})\n\n"
            "| check | status |\n|---|---|\n| drawio | pass |\n| compile | pass |\n"
        )
        (paper / "main.md").write_text(md, encoding="utf-8")

        compiled = await editor_ai.compile_paper(wf_id, source_md="")
        assert compiled["status"] == "completed", compiled
        assert compiled["outputs"]
        output_paths = [workspace / item["path"] for item in compiled["outputs"]]
        assert any(path.suffix.lower() == ".docx" and path.is_file() for path in output_paths)
        assert any(path.suffix.lower() == ".html" and path.is_file() for path in output_paths)
        manifest_path = workspace / compiled["manifest"]["path"]
        assert manifest_path.is_file()
        assert len(compiled["manifest"]["sha256"]) == 64

        converter = get_markdown_to_docx()
        assert converter is not None
        docx_path = paper / "export-python.docx"
        await asyncio.to_thread(converter, paper / "main.md", docx_path, None, workspace, "python")
        assert docx_path.is_file() and docx_path.stat().st_size > 1000
        with zipfile.ZipFile(docx_path) as archive:
            names = set(archive.namelist())
            assert "word/document.xml" in names
            assert any(name.startswith("word/media/") for name in names)

        # Router export path also works against the same workspace.
        response = await export_docx(wf_id, DocxExportRequest(source_file="paper/main.md", engine="python"))
        assert Path(response.path).is_file()
        assert Path(response.path).stat().st_size > 1000

    asyncio.run(go())
