"""Ports owned by the application layer, independent of SQLite or HTTP."""

from __future__ import annotations

from typing import Any, ContextManager, Protocol

from domain.research_run import ArtifactRef, ResearchRun


class ConcurrencyConflict(RuntimeError):
    """Raised when an optimistic revision no longer matches persisted state."""


class EntityNotFound(KeyError):
    """Raised when a requested domain entity is absent."""


class ResearchRepository(Protocol):
    def transaction(self) -> ContextManager[None]: ...
    def create(self, entity: object) -> int: ...
    def get(self, entity_id: str) -> tuple[object, int]: ...
    def update(self, entity: object, expected_revision: int) -> int: ...
    def link(self, from_id: str, to_id: str, relation: str) -> None: ...
    def record_audit(self, audit: object) -> int: ...


class ResearchRunRepository(Protocol):
    """Persistence port for the single canonical research-run aggregate."""

    def transaction(self) -> ContextManager[None]: ...
    def create_run(self, run: ResearchRun) -> None: ...
    def get_run(self, run_id: str) -> ResearchRun: ...
    def save_run(self, run: ResearchRun, expected_version: int) -> None: ...
    def list_runs(self, project_id: str) -> list[ResearchRun]: ...
    def verified_artifacts(self, project_id: str, artifact_ids: list[str]) -> list[dict[str, Any]]: ...
    def project_exists(self, project_id: str) -> bool: ...
