#!/usr/bin/env python3
"""Generate a small TypeScript OpenAPI contract from a saved schema.

The backend remains the contract authority. CI invokes this script against
``openapi.json`` and fails when the checked-in generated artifact drifts.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def ts_type(schema: dict) -> str:
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{ts_type(schema.get('items', {}))}>"
    if kind == "object" or "properties" in schema:
        return "Record<string, unknown>"
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean"}.get(kind, "unknown")


def render(document: dict) -> str:
    lines = ["// Generated by tools/generate_openapi_client.py; do not edit.", ""]
    for name, schema in sorted(document.get("components", {}).get("schemas", {}).items()):
        properties = schema.get("properties", {})
        if not properties:
            continue
        required = set(schema.get("required", ()))
        lines.append(f"export interface {name} {{")
        for key, value in sorted(properties.items()):
            optional = "" if key in required else "?"
            lines.append(f"  {key}{optional}: {ts_type(value)};")
        lines.extend(["}", ""])
    lines.append("export const OPENAPI_PATHS = " + json.dumps(sorted(document.get("paths", {}))) + " as const;")
    lines.append("")
    lines.append("export type OpenApiPath = typeof OPENAPI_PATHS[number];")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("schema", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = render(json.loads(args.schema.read_text(encoding="utf-8")))
    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if current != generated:
            print(f"generated OpenAPI client is stale: {args.output}")
            return 1
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
