"""Deterministic architecture, reachability, and clone audit."""
from __future__ import annotations
import ast
from pathlib import Path
PLACEHOLDERS=("TODO","FIXME","not implemented","fake success")
def _imports(file):
    try: tree=ast.parse(file.read_text(encoding="utf-8",errors="replace"))
    except SyntaxError: return []
    out=[]
    for node in ast.walk(tree):
        if isinstance(node,ast.Import): out.extend(alias.name for alias in node.names)
        elif isinstance(node,ast.ImportFrom) and node.module: out.append(node.module)
    return out
def audit(root: Path) -> dict:
    findings=[]; imports=[]; modules={}; backend=root/"backend"
    for file in backend.rglob("*.py") if backend.exists() else []:
        relative=file.relative_to(root).as_posix(); text=file.read_text(encoding="utf-8",errors="replace"); modules[relative]=_imports(file)
        if "/domain/" in f"/{relative}" and any(x.startswith("infrastructure") for x in modules[relative]): imports += [f"{relative}:{i}" for i,line in enumerate(text.splitlines(),1) if "infrastructure" in line and ("from " in line or "import " in line)]
        if "/domain/" in f"/{relative}" or "/application/" in f"/{relative}": findings += [f"{relative}:{i}" for i,line in enumerate(text.splitlines(),1) if any(marker.lower() in line.lower() for marker in PLACEHOLDERS)]
    legacy={"workflow_engine.py":{"owner":"backend/services","canonical":"workflow engine","deprecated":False,"migration":"No new business logic without a focused module and tests."}}
    router=(backend/"routers/research_runs.py").read_text(encoding="utf-8") if (backend/"routers/research_runs.py").exists() else ""
    duplicate_source=["services.research_orchestrator"] if "services import research_orchestrator" in router else []
    cycles=[]
    for module,deps in modules.items():
        prefix=module[:-3].replace("/", ".")
        if any(dep == prefix or dep.startswith(prefix+".") for dep in deps): cycles.append(module)
    generated=root/"frontend/src/generated/openapi.ts"; generated_ok=generated.exists() and "Generated by tools/generate_openapi_client.py" in generated.read_text(encoding="utf-8")
    return {"passed":not imports and not findings and not duplicate_source and not cycles and generated_ok,"domain_infrastructure_imports":imports,"new_placeholder_findings":findings,"legacy_components":legacy,"import_cycles":cycles,"duplicate_run_sources":duplicate_source,"generated_openapi_client":generated_ok,"production_run_mutation_owner":"application.research_run_engine.ResearchRunEngine"}
if __name__=="__main__":
 import json,sys; report=audit(Path(__file__).resolve().parents[1]); print(json.dumps(report,indent=2)); sys.exit(0 if report["passed"] else 1)
